name: quickboom_hrm
description: "QuickBoom HRM - Human Resource Management System"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter

  # State Management - Riverpod
  flutter_riverpod: ^3.3.1
  riverpod_annotation: ^4.0.2

  # UI & Animations
  cupertino_icons: ^1.0.8
  google_fonts: ^8.1.0
  flutter_animate: ^4.5.0

  # Charts & Analytics
  fl_chart: ^1.2.0

  # Calendar
  table_calendar: ^3.1.2

  # Media / Uploads
  image_picker: ^1.1.2

  # Utilities
  intl: ^0.20.2
  equatable: ^2.0.5
  shared_preferences: ^2.2.3
  local_auth: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  riverpod_generator: ^4.0.3
  build_runner: ^2.4.13
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
