# Uncomment this line to define a global platform for your project
platform :ios, '13.0'

# CocoaPods analytics sends network requests to Apple Intelligence. Use this to disable it.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

target 'Runner' do
  use_frameworks! :linkage => :static

  # Flutter Pods
  pod 'Flutter', :path => File.expand_path('../Flutter')
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
  
  # Disable Swift Package Manager for plugins that don't support it
  installer.pods_project.main_group['Pods'].new_file('.spm-disabled')
end
